### ISSUE TITLE
Google Chrome Not Working At Backround

### ISSUE THREAD

**Issue by mehmetakifsimsek** [SeinopSys/LightningReopen#3]
Hi, I just installed extension and I uncheck "let google chrome run backround" and also click exit.

I reboot there is no icon at notification area. I wanted to recover this so I reinstall chrome and extension but there is no difference.

How could I make this like before?

**Comment by SeinopSys** [comment]
Please open your Chrome settings, search for "background" and toggle the switch to enable Chrome to run in the background.

![image](https://user-images.githubusercontent.com/3200580/132583115-764ebbe2-2763-4599-8330-178e7cbf28a1.png)

**Comment by mehmetakifsimsek** [comment]
Thanks this works.
