### ISSUE TITLE
Every time I reboot my PC, the browser opens automatically

### ISSUE THREAD

**Issue by androidghosh** [SeinopSys/LightningReopen#6]
Works as intended but, every time I reboot/startup my PC, the browser opens automatically. Please fix this.

**Comment by SeinopSys** [comment]
This is a browser built-in behavior that I, as an extension developer, have no control over. You have to manually close the browser before shutting down the machine in order for it to not reopen at startup.

**Comment by androidghosh** [comment]
> You have to manually close the browser before shutting down the machine in order for it to not reopen at startup.

So, Instead of closing the browser from the taskbar every time, I'm using one simple script at win log off to close Vivaldi(chromium) automatically.
`@echo off
taskkill /F /T /IM vivaldi.exe
`
